import streamlit as st


st.header("Youtube Channel", divider=True)

st.markdown(
    "Check out my [YouTube channel](https://www.youtube.com/@JapaneseVideoDictionary) for more Japanese learning content! Each vocabulary word has a dedicated video explaining its meaning, usage, and examples in less than 3 minutes."
)

st.header("Vocabularies", divider="green")
st.markdown(
    "Explore a wide range of Japanese vocabularies categorized by JLPT levels. You can add words to your personal list for review."
)
if st.button("Check out Vocabularies", width="content", type="primary", icon="📚"):
    st.switch_page("src/web/v.py")


st.header("Review with AI", divider="red")
st.markdown(
    "Review your vocabulary words using AI-generated flashcards. Test your knowledge and improve your retention with AI-powered feedback."
)
with st.container(border=True, horizontal=True, horizontal_alignment="center"):
    st.image("resources/Review.png", caption="Review your vocabulary words with AI-generated flashcards.")

st.header("Fill in the Blank", divider="violet")
st.markdown(
    "Practice your Japanese skills with fill-in-the-blank exercises generated by AI. Enhance your comprehension and vocabulary in a fun way."
)
with st.container(border=True, horizontal=True, horizontal_alignment="center"):
    st.image(
        "resources/FillInTheBlank.png",
        caption="Practice your Japanese with AI-generated fill-in-the-blank exercises.",
    )
